# Generated by Django 2.0.4 on 2018-04-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=30, max_digits=40)),
                ('population', models.IntegerField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='GarbageComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='Date complaint was created')),
                ('closed_date', models.DateField(verbose_name='Date complaint was closed')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('score', models.DecimalField(decimal_places=10, max_digits=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage_complaints', to='core.District')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='Date complaint was created')),
                ('closed_date', models.DateField(verbose_name='Date complaint was closed')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('score', models.DecimalField(decimal_places=10, max_digits=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_complaints', to='core.District')),
            ],
        ),
        migrations.AddField(
            model_name='councilmember',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_member', to='core.District'),
        ),
    ]
